apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "kev-the-dev"
  tags: ['data-platform']
  annotations:
    github.com/project-slug: kevinneville/my-namespace-demo
  links:
    - url: https://vcc-consumer-digital.slack.com/archives/C05152521BP
      title: Slack channel
      icon: chat
    - url: https://backstage-staging.volvocars.biz/catalog/default/group/data-platform
      title: Data-Platform Backstage
      icon: dashboard
    - url: https://portal.azure.com/#@volvocars.onmicrosoft.com/resource/subscriptions/5bdbc96f-8160-41e2-a8a8-0ccf75b83a32/resourceGroups/rg-dataops-core-adf-nonprod/overview
      title: Azure Data Factory
spec:
  type: data-workspace
  lifecycle: experimental
  owner: "dc-golden-path"
  system: data-platform
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dc-golden-path
  description: DC Golden Path Team
spec:
  type: team
  profile:
    displayName: DC Golden Path
  children: []  # Add any child groups here, or leave empty if none
  members:
    - user:default/kevin.neville
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: kevin.neville
  description: Kevin Neville, Staff Engineer
spec:
  profile:
    displayName: Kevin Neville
    email: kevin.neville@example.com
  memberOf:
    - group:default/dc-golden-path
