apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dc-golden-path
  description: DC Golden Path Team
spec:
  type: team
  profile:
    displayName: DC Golden Path
  members:
    - user:default/kevin.neville
