apiVersion: platform.example.org/v1alpha1
kind: Pipeline
metadata:
  name: kev-the-dev
  labels:
    prune-group: data-pipelines  
spec:
  pipeline-type: databricks
---
apiVersion: platform.example.org/v1alpha1
kind: Pipeline
metadata:
  name: neville-the-devil
  labels:
    prune-group: data-pipelines  
spec:
  pipeline-type: snowflake
