apiVersion: platform.example.org/v1alpha1
kind: NamespaceClaim
metadata:
  name: example-namespace-claim
spec:
  name: kevinneville-repo-1
  podName: hello-world-pod
  image: busybox
  command: /bin/sh", "-c", "while true; do echo hello world $(date); sleep 1; done
