name: Validate Data Contract

on:
  pull_request:
    branches: [main]

jobs:
  validate-contract:
    name: Verify Data Contract
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install datacontracli
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir --prefer-binary datacontract-cli==0.10.28

      - name: Lint data contract
        run: |
            datacontract lint contracts/my_contract.yaml

